_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS: "./output/R101/model_final.pth" 
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res3", "res4"]
  BACKBONE:
    FREEZE_AT: 5
DATASETS:
  TRAIN: ("coco_2017_train_voc_5_shot",)
  TEST: ("coco_2017_val",)
  TESTSHOTS: 5
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  STEPS: (2000, 3000)
  MAX_ITER: 3500
  WARMUP_ITERS: 200
  START_SAVE_ITER: 2500
  CHECKPOINT_PERIOD_EVA: 100
INPUT:
  FS:
    FEW_SHOT: True
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 4
  MIN_SIZE_TRAIN: (440, 472, 504, 536, 568, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: './output/coco/5shot/'
